### ISSUE TITLE
Read Me

### ISSUE THREAD

**Issue by Hadea4711** [codyc1515/homebridge-sma-inverter#10]
Hi,

Could you be please so kind and add a Read Me for this Plugin? I'm very interested using this Plugin but without readme, I don't know what is to add in the config.json of Homebridge.

Thanks.
Sebastian

**Comment by codyc1515** [comment]
This should be included now since https://github.com/codyc1515/homebridge-sma-inverter/commit/e0db4edc82a3debd8c71ef76478ea042b2fbad74. I have updated this recently as it was not up-to-date (https://github.com/codyc1515/homebridge-sma-inverter/commit/aa9261cbaa9b8f54bfc0c425652adca263022338).

**Comment by mitch7391** [comment]
@codyc1515 am in the market for solar and was likely going with a SMA; just noticed this still doesn't have a proper 'Read Me'. I only bring it up as I was trying to work out if this plug-in will support the SMA Sunny Boy I am looking at.

**Comment by codyc1515** [comment]
Probably it will work. If it's the red one.

**Comment by mitch7391** [comment]
Cheers @codyc1515, looks like iv settled on the SMA anyway as it seems to be quieter and more regularly updated than fronius. So fingers crossed! Haha

**Comment by codyc1515** [comment]
What would be quieter?

**Comment by mitch7391** [comment]
I was looking at either Fronius or SMA for my new system install. Fronius has a cooling fan and can be a louder inverter on hot days, whereas SMA is passively cooled and therefore not as noisy to run :)
