### ISSUE TITLE
Which inverters are supported?

### ISSUE THREAD

**Issue by BionicThomas** [codyc1515/homebridge-sma-inverter#11]
Hi!

My set-up is a SMA STP 7000TL-20 with a Sunny Home Manager an SMA Energymeter.
I think the Inverter itself does not have network connectivity and only communicates via Bluetooth?
Is it possible to get the details from the Energymeter?
Otherwise I'm as well using SBFspot on a Pi to upload data to pvoutput.org
Any furrther info would be appreciated!

**Comment by codyc1515** [comment]
I'm not sure. This plug-in uses ModBus. Does it support ModBus?

**Comment by BionicThomas** [comment]
Hi codyc1515,
looking at the manual, yes!

"
Modbus
Der Wechselrichter ist mit einer Modbus-Schnittstelle ausgestattet. Die Modbus-Schnittstelle ist standardmäßig deaktiviert und muss bei Bedarf konfiguriert werden.
Die Modbus-Schnittstelle der unterstützten SMA Geräte ist für den industriellen Gebrauch konzipiert und hat folgende Aufgaben:
• Ferngesteuertes Abfragen von Messwerten
• Ferngesteuertes Einstellen von Betriebsparametern
• Vorgabe von Sollwerten zur Anlagensteuerung
"
Source: http://files.sma.de/dl/17781/STP5-12TL-20-BE-de-15.pdf

Is there somewhere a guide on how to configure your plugin that I can follow?

**Comment by codyc1515** [comment]
Did you try it?

**Comment by codyc1515** [comment]
Did you try it? There is config-ui-x support now so set-up should be easy.
