### ISSUE TITLE
Sunny Tripower and Homebridge 0.4.53 - no updated values, but successful connection

### ISSUE THREAD

**Issue by PA7T** [codyc1515/homebridge-sma-inverter#13]
I used #7 manual fix to successfully connect to my Sunny Tripower (identical holding registers as Sunny Boy AFAIK). I can also see the icon in the Home app, but it does only show the template values for serial etc.
In debug mode only polling of the following characteristic is logged:
Get On
Get OutletInUse

Any idea what is going wrong?

Thanks!

**Comment by codyc1515** [comment]
Hopefully the IP address issue should be fixed now in https://github.com/codyc1515/homebridge-sma-inverter/commit/94d1c2cd2b33ccf5b3542ac57defab978135c1c9. Can you let me know?

**Comment by codyc1515** [comment]
Closing due to no response.
