### ISSUE TITLE
What is the sense of this plugin?

### ISSUE THREAD

**Issue by drheck** [codyc1515/homebridge-sma-inverter#14]
Hi,
i have installed this plugin and i have a simple switch in my HomeApp?
I thought i can see some values or something else?
Do you have a sample screenshot of that what i can see or what this plugin does?
Thanks a lot for your answer.
Peter

**Comment by codyc1515** [comment]
Yes - you can see them in the Eve app.

**Comment by drheck** [comment]
Ah. Okay.
Thank you. I see it.
I close this issue.
