### ISSUE TITLE
Question: How to integrate 2 SMA Inverters as one Item?

### ISSUE THREAD

**Issue by drheck** [codyc1515/homebridge-sma-inverter#15]
Hello Cody,

i have tried to modify the index.js code in order to get a sum for the customkilowatt of 2 inverters.
But i can not get the registers from a second client2 (i have copied the _connect code and the _refresh code for a second client).

I have added my files. 
If i activate _connect2 i get an error in _refresh2 - why? 
It is the same code as in _connect.

	this._connect2(true);	//Error Why?
/*	
Aug  9 16:22:37 hbridge3 homebridge[453]: [2020-8-9 16:22:37] [SMA 3.6/4.0] Connecting Host: 192.168.xxx.aa
Aug  9 16:22:37 hbridge3 homebridge[453]: [2020-8-9 16:22:37] [SMA 3.6/4.0] Connected
Aug  9 16:22:37 hbridge3 homebridge[453]: [2020-8-9 16:22:37] [SMA 3.6/4.0] Connecting host2: 192.168.xxx.bb
Aug  9 16:22:37 hbridge3 homebridge[453]: [2020-8-9 16:22:37] [SMA 3.6/4.0] Connected hostname2
Aug  9 16:22:37 hbridge3 homebridge[453]: (node:453) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 192.168.xxx.bb:502
Aug  9 16:22:37 hbridge3 homebridge[453]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
Aug  9 16:22:37 hbridge3 homebridge[453]: (node:453) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
Aug  9 16:22:39 hbridge3 homebridge[453]: [2020-8-9 16:22:39] [SMA 3.6/4.0] Updating status host2 XXX-> vorher
Aug  9 16:22:39 hbridge3 homebridge[453]: [2020-8-9 16:22:39] [SMA 3.6/4.0] Refresh failed Attempting reconnect... TypeError: Cannot read property 'buffer' of undefined
Aug  9 16:22:39 hbridge3 homebridge[453]:     at SMAInverter.<anonymous> (/usr/local/lib/node_modules/homebridge-sma-inverter/index.js:277:17)
Aug  9 16:22:39 hbridge3 homebridge[453]:     at ModbusRTU.writeFC4 (/usr/local/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/index.js:544:19)
Aug  9 16:22:39 hbridge3 homebridge[453]:     at ModbusRTU.writeFC3 (/usr/local/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/index.js:530:10)
Aug  9 16:22:39 hbridge3 homebridge[453]:     at ModbusRTU.converted [as readHoldingRegisters] (/usr/local/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/apis/promise.js:36:27)
Aug  9 16:22:39 hbridge3 homebridge[453]:     at SMAInverter._refresh (/usr/local/lib/node_modules/homebridge-sma-inverter/index.js:276:12)
Aug  9 16:22:39 hbridge3 homebridge[453]:     at SMAInverter.<anonymous> (/usr/local/lib/node_modules/homebridge-sma-inverter/index.js:151:9)
Aug  9 16:22:39 hbridge3 homebridge[453]:     at listOnTimeout (internal/timers.js:549:17)
Aug  9 16:22:39 hbridge3 homebridge[453]:     at processTimers (internal/timers.js:492:7)
*/	

	//this._connect(true);	//Okay

Do you have an idea?

I have 2 inverters (as single items no problem), but i want to get the values for both as a sum.
Thank you very much for an answer.

regards,
Peter
[dph2.zip](https://github.com/codyc1515/homebridge-sma-inverter/files/5056451/dph2.zip)

**Comment by codyc1515** [comment]
Hi there Peter

Apologies. I must have missed the email for this ticket and do not revise the plug-in that often. To be quite honest to support this you would really need to re-develop the plug-in as a "platform". Many plug-ins are written this way. Unfortunately I do not know how so cannot easily assist with this. I would welcome any help converting the plug-in to a platform. I also don't have two inverters to test with. You may wish to look at integrating with Home Assistant to meet your needs.

Kind regards
Cody
