### ISSUE TITLE
SMA Webbox?

### ISSUE THREAD

**Issue by apographon** [codyc1515/homebridge-sma-inverter#2]
Does this connect to the SMA WebBox as well?

**Comment by ceraz68** [comment]
Hi tried to connect between my homebridge server and the SMA on the same wired LAN without success.

Can you explain "hostname": "sma1002000200" in the config.json file as I can't access the inverter.


When I connect locally to the SMA inverter by its IP address (192.168.1.88), I land on the page http://192.168.1.88/#/home
Where I have a username/password page

When I manually try http://192.168.1.88/dyn/login.json in the browser
I get an error 404

Thanks

**Comment by codyc1515** [comment]
@apographon I am not sure as I do not have one of these devices. I have recently upgraded the plug-in to connect using the SMA ModBus protocol (whereas before it was HTTP, which was device specific). I intend to add the web specific support back soon as a fallback. Can you please check if your device supports ModBus?

@ceraz68 Can you please raise a separate issue for this? It sounds like your device may be unsupported.
