### ISSUE TITLE
ERROR: connect ECONNREFUSED

### ISSUE THREAD

**Issue by mitch7391** [codyc1515/homebridge-sma-inverter#21]
Hi @codyc1515 I have just had my SMA Sunny Boy 5.0 (red model) installed but am having no luck with the plug-in. I have been able to access it through the web-portal and through the provided apps; so I know it is online. I noticed in an old issue raised by someone else you told them that this meant that the model does not support modbus, but I had confirmed with the installer before buying this model that it does. Any tips?

![image](https://user-images.githubusercontent.com/40288237/102492523-c5ae0200-40ac-11eb-8b98-fc41b3435e98.png)

**Comment by richardmayer** [comment]
Hello,

I struggled with the same problem for the last 30 Minutes with my Tripower inverter.
Did you make sure, that ModBus TCP and UDP-Ports are enabled in the inverter settings?
(Login via "installer", activate the TCP and UDP Servers under "Device Parameters" => "External Communication")

After doing that, reading the data works just fine.
![image](https://user-images.githubusercontent.com/28772465/102547797-03fdee00-40ba-11eb-9f4a-38dcdaee4e60.png)

Best regards

Richard

**Comment by mitch7391** [comment]
Hey @richardmayer thanks for this info! I got to the webpage for this but did not know the password for the `user` or `installer` logins. Would you happen to know them? I assume they will be generic.

**Comment by mitch7391** [comment]
I did a quick google and found the generic `user` password is `0000` and the generic `installer` password is `1111`. This did not work for me, so it would appear my installer changed the password during installation...

**Comment by mitch7391** [comment]
@richardmayer my solar installer was kind enough to give me the `installer` password; which I did not expect. Thanks to your advice, I am all up and running! @codyc1515 do you think this information could go in future README file to help the next person and hopefully reduce future issues being created?
