### ISSUE TITLE
100,000kWh Bug For Today Reading

### ISSUE THREAD

**Issue by mitch7391** [codyc1515/homebridge-sma-inverter#22]
Hi @codyc1515 I can see there has been a previous issue with a bug displaying 100,000kWh for the some readings based on your commits. I noticed today I have the bug:

![B6726728-4130-416E-A7FF-B5E2E1F67FF2](https://user-images.githubusercontent.com/40288237/102735321-0b085300-437d-11eb-8008-ea635085e375.png)

The inverter is currently running and pulling kWh and the value for ‘Today’ as I type is only 13.1kW; so I can’t imagine it is an issue of too high of a value. Hope this helps!

**Comment by MAPEZ1** [comment]
Hi, yes...  same here.

![image](https://user-images.githubusercontent.com/76261897/102781501-1026cb80-4398-11eb-9e4a-8fd861e8682b.png)
100k value is also shown during night.

**Comment by mitch7391** [comment]
@codyc1515 do you think this could be a problem with the wrong modbus register being read for some models? I looked the following document and can where you may have picked the parameters in chapter 5.3 (page 27) but was wondering if it should use the parameters from 5.4.1 (page 28)? However the issue with using this second tale is the parameter is a different data type (U64 instead of U32) and I am not sure if that is something you can get around?

[WEBBOX-MODBUS-TB-en-19.pdf](https://studylib.net/doc/25277802/webbox-modbus-tb-en-19)

Hope this helps :)

**Comment by mitch7391** [comment]
According to that manual the generic parameters you have picked will only work with across all models that have a Unit ID of 2; I have just found out mine has a Unit ID of 3 and therefore would use the parameters from chapter 5.4.1. This could be why this is not working for people. This can be changed from the web portal when logged in as `installer`, but I am not sure if there are any consequences to changing the Unit ID from 3 to 2, so at this stage I will not be testing that to see if it fixes my issue...

**Comment by mitch7391** [comment]
New Homebridge v1.3.0-beta.40 actually displays a warning for this:

> [04/01/2021, 11:04:09] Received warning for the plugin 'homebridge-sma-inverter' from the characteristic 'Current Ambient Light Level': characteristic was supplied illegal value: number 4294967.295 exceeded maximum of 100000.

> [Current` Ambient Light Level@Homebridge B03F] characteristic was supplied illegal value: number 4294967.295 exceeded maximum of 100000.

`4294967.295` being the maximum value for a 32bit unassigned integer. So I would say this further supports my case that for inverters with `UNIT ID` not equal to `2`, then this characteristic will not work. I am still waiting for a reply form my solar suppliers tech team to see if there are any issues with changing the `UNIT ID`; the Christmas and New Year break has slowed this response down a bit.

**Comment by mitch7391** [comment]
This issue appears to now be resolved for me.
