### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Stefan-83** [codyc1515/homebridge-sma-inverter#26]
Hi,
getting this error message.

> [05/03/2021, 14:59:46] [SMA Inverter] Attempting connection SMA3002853535.local
[05/03/2021, 14:59:46] [SMA Inverter] Connection successful
(node:13854) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 192.168.178.91:502
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
(node:13854) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 129)

Using SHM2.0

**Comment by MAPEZ1** [comment]
--> Using SHM2.0
Not sure that it would work with SHM..... from what I could read in the issues, it uses the modbus registers from inverters.
For the plugin to work you need to have modbus enabled on the inverter and connect to them.
You may need to check with your installer if modbus is not enabled.

**Comment by codyc1515** [comment]
This plug-in does not work with the Sunny Home Manager, sorry.

**Comment by mitch7391** [comment]
Good to close out @codyc1515?
