### ISSUE TITLE
SMA Inverter Hostname ?

### ISSUE THREAD

**Issue by Stefan-83** [codyc1515/homebridge-sma-inverter#28]
Hi,
I'm successfully using openhab2 with [SMA Energy Meter Binding](https://www.openhab.org/addons/bindings/smaenergymeter/).
The Energy Meter is discovered by receiving data on the default multicast IP address.
![image](https://user-images.githubusercontent.com/52136837/111035792-53835a00-841c-11eb-9dc2-980c50b1c9e7.png)

When looking into my SMA-DeviceOverview:
![image](https://user-images.githubusercontent.com/52136837/111035748-1b7c1700-841c-11eb-8c84-1ba0951e0908.png)
Which is the correct device for this Plugin?
And where I can obtain the correct SMA Inverter Hostname?
![image](https://user-images.githubusercontent.com/52136837/111035871-af4de300-841c-11eb-839b-a36fb07786e2.png)

When I ping the SMA-device in my home network, I get this IP address in return:
![image](https://user-images.githubusercontent.com/52136837/111035855-9c3b1300-841c-11eb-9760-32118bb8abb3.png)

**Comment by codyc1515** [comment]
This plug-in is written for the Sunny Boy line of inverters, not the Energy Meter or the TriPower. To support either of these would likely require an entire re-write of the plug-in, sorry, and I do not have one to test with. In my country the energy meter alone is over US$1,000.

**Comment by mitch7391** [comment]
I do not see this one listed in the [modbus document](https://studylib.net/doc/25277802/webbox-modbus-tb-en-19) and from the screenshots above does not appear the use modbus based on the port referenced and therefore not compatible with this plug-in. Are we good to close this one out?
