### ISSUE TITLE
modbus-serial issue

### ISSUE THREAD

**Issue by rangerek** [codyc1515/homebridge-sma-inverter#3]
`Oct 16 09:14:35 homebridge homebridge[2002]: [10/16/2019, 9:14:35 AM] ERROR LOADING PLUGIN homebridge-sma-inverter:
Oct 16 09:14:35 homebridge homebridge[2002]: [10/16/2019, 9:14:35 AM] Error: Cannot find module 'modbus-serial'
Oct 16 09:14:35 homebridge homebridge[2002]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
Oct 16 09:14:35 homebridge homebridge[2002]:     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
Oct 16 09:14:35 homebridge homebridge[2002]:     at Module.require (internal/modules/cjs/loader.js:637:17)
Oct 16 09:14:35 homebridge homebridge[2002]:     at require (internal/modules/cjs/helpers.js:22:18)
Oct 16 09:14:35 homebridge homebridge[2002]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-sma-inverter/index.js:4:17)
Oct 16 09:14:35 homebridge homebridge[2002]:     at Module._compile (internal/modules/cjs/loader.js:689:30)
Oct 16 09:14:35 homebridge homebridge[2002]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
Oct 16 09:14:35 homebridge homebridge[2002]:     at Module.load (internal/modules/cjs/loader.js:599:32)
Oct 16 09:14:35 homebridge homebridge[2002]:     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
Oct 16 09:14:35 homebridge homebridge[2002]:     at Function.Module._load (internal/modules/cjs/loader.js:530:3)`
just to let you know i did 
`npm install modbus-serial` before posti g the issue

**Comment by codyc1515** [comment]
npm install -g modbus-serial should work

**Comment by rangerek** [comment]
addnig --unsafe-perm worked :) 

but now there is a next question:
`Oct 16 10:31:03 homebridge homebridge[2920]: [10/16/2019, 10:31:03 AM] TypeError: Cannot read property 'buffer' of undefined
Oct 16 10:31:03 homebridge homebridge[2920]:     at SMAInverter.<anonymous> (/usr/local/lib/node_modules/homebridge-sma-inverter/index.js:131:17)
Oct 16 10:31:03 homebridge homebridge[2920]:     at ModbusRTU.writeFC4 (/usr/local/lib/node_modules/modbus-serial/index.js:501:19)
Oct 16 10:31:03 homebridge homebridge[2920]:     at ModbusRTU.writeFC3 (/usr/local/lib/node_modules/modbus-serial/index.js:487:10)
Oct 16 10:31:03 homebridge homebridge[2920]:     at ModbusRTU.converted [as readHoldingRegisters] (/usr/local/lib/node_modules/modbus-serial/apis/promise.js:36:27)
Oct 16 10:31:03 homebridge homebridge[2920]:     at SMAInverter.<anonymous> (/usr/local/lib/node_modules/homebridge-sma-inverter/index.js:130:11)
Oct 16 10:31:03 homebridge homebridge[2920]:     at ontimeout (timers.js:436:11)
Oct 16 10:31:03 homebridge homebridge[2920]:     at tryOnTimeout (timers.js:300:5)
Oct 16 10:31:03 homebridge homebridge[2920]:     at listOnTimeout (timers.js:263:5)
Oct 16 10:31:03 homebridge homebridge[2920]:     at Timer.processTimers (timers.js:223:10)`

is it because somethnig is not enabled on my SMA or is it because my SMA is 6.0 and is not on the list?

**Comment by codyc1515** [comment]
You need to have ModBus enabled.
