### ISSUE TITLE
characteristic value expected valid finite number and received "undefined" 

### ISSUE THREAD

**Issue by pbanane** [codyc1515/homebridge-sma-inverter#30]
Hi,

just installed the plugin and first setup was quite easy. I have a SMA TriPower 8000 with SHM 2.0.
After the restart I got the current solar level, todays total and overall total. 
And I got some warnings:
characteristic value expected valid finite number and received "undefined" 

> 
> [13/04/2021, 20:34:15] [homebridge-sma-inverter] This plugin generated a warning from the characteristic 'Current Ambient Light Level': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
> [13/04/2021, 20:34:15] [homebridge-sma-inverter] This plugin generated a warning from the characteristic 'Amperes': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
> [13/04/2021, 20:34:15] [homebridge-sma-inverter] This plugin generated a warning from the characteristic 'Total Consumption': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
> [13/04/2021, 20:34:15] [homebridge-sma-inverter] This plugin generated a warning from the characteristic 'Volts': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
> [13/04/2021, 20:34:15] [homebridge-sma-inverter] This plugin generated a warning from the characteristic 'Consumption': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
> [13/04/2021, 20:34:15] [homebridge-sma-inverter] This plugin generated a warning from the characteristic 'Current Ambient Light Level': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.
> [13/04/2021, 20:34:15] [homebridge-sma-inverter] This plugin generated a warning from the characteristic 'Current Ambient Light Level': characteristic value expected valid finite number and received "undefined" (undefined). See https://git.io/JtMGR for more info.

Would be nice to get some more data in homekit but I do not know if this is an issue with my setup, a bug or even my personal incompetence or lack of knowlege :-)

**Comment by mitch7391** [comment]
Is this still an issue for you @pbanane?
