### ISSUE TITLE
No data coming in

### ISSUE THREAD

**Issue by hansmestrum** [codyc1515/homebridge-sma-inverter#31]
Installed the plugin in HomeBridge. I could not find what to do so just entered the IP.
After restarting I see 3 devices but no data coming in.
Should I do more?
I have a SMA STP5

**Comment by codyc1515** [comment]
Tripower is not currently supported.

**Comment by WiesiDeluxe** [comment]
It is possible for you to add Support for Tripower, i also have a SMA STP 5000TL-20!?

**Comment by codyc1515** [comment]
Well I guess it’s possible if someone wants to send me one.

**Comment by Auka84** [comment]
Hi, what do you need to implement the compatibily with tripower ? I also have a tripower and it doesn't work :(

**Comment by javab0y** [comment]
Expressing my interest in the TriPower too Sunny Tripower 5000TL-20. 
Thank you.

**Comment by codyc1515** [comment]
Does anyone have information on the ModBus protocol for TriPower? I imagine it's not that hard.

**Comment by Auka84** [comment]
Perhaps here https://www.sma.de/fr/produits/fonctionnalites-interfaces/interface-protocole-modbus.html

**Comment by mitch7391** [comment]
@codyc1515 as mentioned in #33, the link I have placed there could be of help for this issue.
