### ISSUE TITLE
Plugin down?

### ISSUE THREAD

**Issue by WesleyLiekens** [codyc1515/homebridge-sma-inverter#33]
Is this Plugin end of life?
i had to reinstall my homebridge on another device after a crash and it seems that this plugin won't install anymore
in homebridge it says homebridge-sma-inverter v3.2.1
but when I open the link to GitHub its only on 2.0.0
When I instal 2.0.0 it won't work
and when I install from homebridge for v3.2.1 I get

npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/homebridge-sma-inverter/node_modules/@serialport/bindings
npm ERR! command failed
npm ERR! command sh -c prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.3.0
npm ERR! gyp info using node@16.13.0 | darwin | x64
npm ERR! gyp info find Python using Python version 3.10.0 found at "/Library/Frameworks/Python.framework/Versions/3.10/bin/python3"
npm ERR! gyp info spawn /Library/Frameworks/Python.framework/Versions/3.10/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/homebridge-sma-inverter/node_modules/@serialport/bindings/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/wesleyliekens/Library/Caches/node-gyp/16.13.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/wesleyliekens/Library/Caches/node-gyp/16.13.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/wesleyliekens/Library/Caches/node-gyp/16.13.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/local/lib/node_modules/homebridge-sma-inverter/node_modules/@serialport/bindings',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
npm ERR! 
npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
npm ERR! 
npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
npm ERR! 
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 21.1.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /usr/local/lib/node_modules/homebridge-sma-inverter/node_modules/@serialport/bindings
npm ERR! gyp ERR! node -v v16.13.0
npm ERR! gyp ERR! node-gyp -v v8.3.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wesleyliekens/.npm/_logs/2021-11-19T20_36_02_191Z-debug.log

**Comment by mitch7391** [comment]
@codyc1515 are there any plans to pick this plugin back up? No pressure if not, just would like to know if this plugin is abandoned or not.

**Comment by codyc1515** [comment]
I'm not able to test this on Mac easily, though I'd imagine that's the issue.

**Comment by mitch7391** [comment]
I personally do not have the issue above, I just highjacked this issue to ask if the plugin is still supported based on the 'end of life' question asked above.

**Comment by codyc1515** [comment]
I can't provide support for node-gyp sorry

**Comment by mitch7391** [comment]
Not what I was asking but all good.

**Comment by WesleyLiekens** [comment]
but it has always worked on my Mac flawlessly so im not thinking its because Mac itself

also...
i noticed that in homebridge itself the plugin is updated to 3.3.0
Yet here it still says 2.0.0
could this be something to do with the errors?

**Comment by mitch7391** [comment]
I would hazard a guess that is because both version numbers are quoted in the `package.json` and I have no idea why. The version number you see in Homebridge will be what is published to npm, I wouldn’t be worried about the latest version number seen on GitHub though. It just means a release was never done here to match the one in npm; which is not the best practise but not the end of the world… The one that matters at the end of the day is the one that shows up in npm and Homebridge.

**Comment by WesleyLiekens** [comment]
ok thanks for the info

**Comment by codyc1515** [comment]
Did you resolve the issue? Just again reiterating that this is not a SMA specific plug-in issue but rather an issue with one of the dependencies.

**Comment by mitch7391** [comment]
I could try and install Homebridge on my wife's Mac and see if the same issue is experienced if everyone would like? I actually do not see any of the dependencies mentioned in the errors above in the dependencies section of the `package.json`:

```json

  "dependencies": {
    "fakegato-history": "^0.5.5",
    "modbus-serial": "^7.7.3",
    "moment": "^2.24.0",
    "utils": "^0.3.1"
  }
```
I am still quite new to all of this @codyc1515, but the `package.json` you have is very different to most I have looked at. Are you able to explain a little about the start of it and why it references `v2.2.2` of your plug-in?

**Comment by WesleyLiekens** [comment]
Well I was able to install it again but it got a shitload of errors when installing and even in de log when homebridge is running

**Comment by WesleyLiekens** [comment]
[2/5/2022, 6:26:40 PM] [SMA Inverter] Child bridge process ended
[2/5/2022, 6:26:40 PM] [SMA Inverter] Process Ended. Code: 1, Signal: null
[2/5/2022, 6:26:47 PM] [SMA Inverter] Restarting Process...
[2/5/2022, 6:26:47 PM] [SMA Inverter] Launched child bridge with PID 75381
[2/5/2022, 6:26:48 PM] Registering accessory 'homebridge-sma-inverter.SMAInverter'
[2/5/2022, 6:26:48 PM] [SMA Inverter] Loaded homebridge-sma-inverter v3.3.0 child bridge successfully
[2/5/2022, 6:26:48 PM] Loaded 0 cached accessories from cachedAccessories.0E2D50F6739A.
[2/5/2022, 6:26:48 PM] Homebridge v1.4.0 (HAP v0.10.0) (SMA Inverter) is running on port 33269.
[2/5/2022, 6:26:49 PM] [SMA Inverter] Refresh failed Attempting reconnect... TypeError: Cannot read properties of undefined (reading 'buffer')
    at SMAInverter.<anonymous> (/usr/local/lib/node_modules/homebridge-sma-inverter/index.js:168:13)
    at ModbusRTU.writeFC4 (/usr/local/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/index.js:544:19)
    at ModbusRTU.writeFC3 (/usr/local/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/index.js:530:10)
    at ModbusRTU.converted [as readHoldingRegisters] (/usr/local/lib/node_modules/homebridge-sma-inverter/node_modules/modbus-serial/apis/promise.js:36:27)
    at SMAInverter._refresh (/usr/local/lib/node_modules/homebridge-sma-inverter/index.js:166:11)
    at SMAInverter.<anonymous> (/usr/local/lib/node_modules/homebridge-sma-inverter/index.js:99:8)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

**Comment by mitch7391** [comment]
Now the issue sounds like in #32, which I think means you need to log into your inverter’s web portal and activate modbus.

**Comment by WesleyLiekens** [comment]
Seems like it. Except that it is activated...

**Comment by WesleyLiekens** [comment]
![278010B2-CA67-4B72-89C1-AF75749AC3E7](https://user-images.githubusercontent.com/63705562/152678763-1e19e947-1007-4f0d-b2ec-8c43e7dd51af.jpeg)

**Comment by mitch7391** [comment]
That is a bugger, looks like it should be all good. And you are sure you have not done anything silly like used the wrong IP address (like in the case of not having a static IP a set)?

What model inverter do you have? I think I remember Cody saying some models are not supported…

**Comment by WesleyLiekens** [comment]
> That is a bugger, looks like it should be all good. And you are sure you have not done anything silly like used the wrong IP address (like in the case of not having a static IP a set)?
> 
> What model inverter do you have? I think I remember Cody saying some models are not supported…

That's the thing. it has always worked fine until my computer crashed and I had to reinstall everything 
Its a sunnyboy SB4000TL
IP adress is and has always been 192.168.0.4 (ip reservation from my router)

ps. im have a configuration working in Home Assistant so I am very confident its not on the SMA side

**Comment by WesleyLiekens** [comment]
I remember that when I first installed the plugin I had to manually make a change in the index.js file
I think I needed to add the ip and port 502 or something. but can't seem to find what it was

**Comment by mitch7391** [comment]
Modus always uses port 502, so I would think that the plug-in is using that correctly. So I find that a bit strange, but can’t speak for the inner workings of the plug-in myself sorry…

**Comment by codyc1515** [comment]
SB4000TL may be the issue here. I really need to take a look at the registers to see if this might be the issue. Also the devices emit a packet which allows you to auto detect the devices details which we need to add too.

**Comment by mitch7391** [comment]
@codyc1515 I think this [document](https://studylib.net/doc/25277802/webbox-modbus-tb-en-19) will be exactly what you need. It also details the registers of models I have seen people asking about in your other open issues; meaning you may be able to easily add support for those.

Chapter 5 (page 25) and onwards details the commonly used registers for the different `UNIT ID`'s. I think page 33 might be the right area that details Wesley's model.
