### ISSUE TITLE
Value shows in lux

### ISSUE THREAD

**Issue by hunkyn** [codyc1515/homebridge-sma-inverter#34]
I have a sunny boy 7.7 inverter and i]for some reason it shows values in lux. Is there a setting I need to add to read it correctly?

**Comment by codyc1515** [comment]
What were you expecting? There's no way to show kWh or any power measure for that matter in Home app.

**Comment by hunkyn** [comment]
Ok that is why i was asking if i missed any settings. Interesting that Home app does not have this capability.
