### ISSUE TITLE
Homekit shows "lux" instead of kW and kWh

### ISSUE THREAD

**Issue by raimund-hdr** [codyc1515/homebridge-sma-inverter#37]
**Paste of Logs:**
```

```

**Config:**

```json


```

**Screenshots:**

**Inverter:**

* **Model:** 

**Homebridge Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **homebridge-sma-inverter Version**: 
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / Docker / other

**Comment by solbadguy2010** [comment]
Hi Raimund,
Homekit does not know what a Solar Inverter are. Apple has no device class for these devices. Therefore. As usual with Homebridge, a Plugin developer uses the next best thing. In this case a Lux-Meter.
For example mit Vacuum Robot is a fan...

There is no way for the developer of this Plugin to change Lux to Wh

Timo

**Comment by wimleers** [comment]
What @solbadguy2010 says 😊 

I think this can be closed.

**Comment by raimund-hdr** [comment]
So sad - Apple should do better,

**Comment by wimleers** [comment]
Sad indeed! Hopefully Matter will add it in the not too distant future 😊
