### ISSUE TITLE
Enough Power available Signal

### ISSUE THREAD

**Issue by solbadguy2010** [codyc1515/homebridge-sma-inverter#39]
**Is your feature request related to a problem? Please describe:**
I have a Dishwasher, washing machine and car, that are smart and can be started runnung/charging via Homekit. Currently i can only use the "current" Lux value to tell all of them to start when this value is higher than X. I would like to have this a little more flexible

**Describe the solution you'd like:**
I would like to set up "signals" in the settings like "more than 2kWh for more then 10 minutes" and "more than 4kWh for 30 minutes". Every single signal set up should appear in Homekit as switches that activate themself when the condition is met (and deactivate also). This way i could set up automations like "start the dishwasher when there are 2kW available for more than 10 Minutes". 

**Describe alternatives you've considered:**
External Plugins that use the Lux reading from your Plugin, but i have not found one.

**Inverter:**

* **Model:** STP 8000TL-20

**Comment by mitch7391** [comment]
@solbadguy2010 have you considered using other apps like 'Eve' to create more complicated automations? I have not dabbled too much myself, but you can create better automations there from what I have heard.

**Comment by solbadguy2010** [comment]
Hi, yes. Thank you. I have already done that, but i was not able to manage this mechanic mentioned above. But yes, i am as good as it gets currently.

**Comment by mitch7391** [comment]
Another suggestion and one I have not used, but could be worth checking out [dummy switches](https://github.com/nfarina/homebridge-dummy) and see if that can help you out.

**Comment by wimleers** [comment]
I too am very interested in this!
