### ISSUE TITLE
Support for SunnyBoy 3.6

### ISSUE THREAD

**Issue by ceraz68** [codyc1515/homebridge-sma-inverter#4]
Hi tried to connect between my homebridge server and the SMA (SunnyBoy 3.6 1AV-40) on the same wired LAN without success.

Can you explain "hostname": "sma1002000200" in the config.json file as I can't access the inverter.

When I connect locally to the SMA inverter by its IP address (192.168.1.88), I land on the page http://192.168.1.88/#/home
Where I have a username/password page

When I manually try http://192.168.1.88/dyn/login.json in the browser
I get an error 404

Thanks

**Comment by codyc1515** [comment]
You need to have ModBus enabled. Use _192.168.1.88_ as your hostname.
