### ISSUE TITLE
[Feature Request] SMA Home manager support

### ISSUE THREAD

**Issue by mbnn** [codyc1515/homebridge-sma-inverter#41]
Hello,

I would like to request to get the SMA Home Manager 2.0 supported so we can read current power consumption (+ and -) if possible in Homekit.

**Inverter:**
https://www.sma.de/en/products/monitoring-control/sunny-home-manager-20.html

**Comment by TheRealGros** [comment]
I support this request.

**Comment by wimleers** [comment]
+1

**Comment by Kragothius** [comment]
+1

**Comment by wimleers** [comment]
I _sort of_ found examples of how to do this! Or at least the following two projects claim to support reading data from the SMA Home Manager and SMA Energy Meter:
- https://github.com/RalfOGit/sma-emeter-and-inverter-to-influxdb-cpp
- https://github.com/mincequi/SBFspot

**Comment by wimleers** [comment]
FYI: I've got a custom plugin for exposing SMA Home Manager 2.0 to HomeKit in the works. I will publish it in the coming months. I'm currently still refining it. For some reason, automations won't trigger when I use this new accessory in automations 😬

**Comment by TheRealGros** [comment]
👍

**Comment by Kragothius** [comment]
Worth to wait. ThanksAm 04.10.2022 um 19:09 schrieb Wim Leers ***@***.***>:﻿
FYI: I've got a custom plugin for exposing SMA Home Manager 2.0 to HomeKit in the works. I will publish it in the coming months. I'm currently still refining it. For some reason, automations won't trigger when I use this new accessory in automations 😬
