### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by dannywanwan** [codyc1515/homebridge-sma-inverter#43]
I would like to request the option of displaying the current values in Watts (i.e kWx1000)
HomeKit allows automations to be triggered by changing values, but only 10/20/50/100/200/400/600/etc so a different unit would allow greater control of this. 
My unit is 5kW so aren’t able to currently utilise this function.

**Comment by wimleers** [comment]
This is already supported! See https://github.com/codyc1515/homebridge-sma-inverter/blob/master/index.js#L172.

It's a bit odd, but you'll see it in the Eve App listed under "SMA Inverter Currently", then tap "Consumption".

I have several automations based on this, and it works fine :)
